name: Build Test and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.400
    - name: Restore dependencies
      run: dotnet restore
    - name: Install build tools
      run: sudo apt-get install gettext
    - name: Build CircuitPythonNative.dll
      run: make bin/CircuitPythonNative.dll
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Package
      run: make pack
    - name: Upload Package
      uses: actions/upload-artifact@master
      with:
        path: PackageOut
