name: Build Test and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Update Versions
      env:
        VERSION_PREFIX: '0.3'
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" src/CircuitPython.csproj
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.400
    - name: Install Iril
      run: dotnet tool install --global iril-cli
    - name: Restore dependencies
      run: dotnet restore
    - name: Install build tools
      run: sudo apt-get install gettext
    - name: Build CircuitPythonNative.dll
      run: make bin/CircuitPythonNative.dll
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Package
      run: make pack
    - name: Upload Package
      uses: actions/upload-artifact@master
      with:
        path: PackageOut
